# Generated by Django 2.1.1 on 2018-09-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productanswer',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productquestion',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
